export const MY_SKILLS_DATA = [
  {
    id: 1,
    type: "education",
    date: "2014 - 2018",
    title: "Bachelor degree",
    subtitle: "MIPT, Moscow Institute of Physics and Technology",
    text: "Major: Applied Mathematics and Physics",
    labels: ["Science"],
  },
  {
    id: 2,
    type: "education",
    date: "2017",
    title: "True random number generator in FGPA",
    subtitle: "60th MIPT Scientific Conference (172-173 pages)",
    text: "",
    labels: ["Science"],
    link: "https://abitu.net/public/admin/mipt-conference/FRKT.pdf",
  },
  {
    id: 3,
    type: "pet",
    date: "2022",
    title: "Portfolio page",
    subtitle: "",
    text: "React js + Material UI",
    labels: ["Web"],
    link: "https://github.com/yashart",
  },
  {
    id: 4,
    type: "pet",
    date: "2022",
    title: "LTE Signal auto-guided amplifier",
    subtitle: "",
    text: "Full path from design to implementation. Device + mobile app.",
    labels: ["Other"],
    photo: "static/imgs/amplifier.jpg",
    link: "",
  },
  {
    id: 99,
    type: "work",
    date: "2001 - present",
    title: "Creative Director",
    subtitle: "Miami, FL",
    text: "Creative Direction, User Experience, Visual Design, Project Management, Team Leading",
    labels: ["ROS", "Open CV"],
    photo: "static/imgs/test.jpeg",
    link: "",
  },
  {
    id: 2,
    type: "volunteer",
    date: "2001 - present",
    title: "Creative Director2",
    subtitle: "Miami, FL",
    text: "Creative Direction, User Experience, Visual Design, Project Management, Team Leading",
    labels: ["ROS", "Open CV", "Social"],
    photo: "",
    link: "https://google.com",
  },
  {
    id: 103,
    type: "education",
    date: "2001 - present",
    title: "Creative Director3",
    subtitle: "Miami, FL",
    text: "Creative Direction, User Experience, Visual Design, Project Management, Team Leading",
    labels: ["ROS"],
    photo: "static/imgs/test.jpeg",
    link: "https://ya.ru",
  },
  {
    id: 104,
    type: "pet",
    date: "2001 - present",
    title: "Creative Director4",
    subtitle: "Miami, FL",
    text: "Creative Direction, User Experience, Visual Design, Project Management, Team Leading",
    labels: ["ROS", "Open CV"],
    photo: "",
    link: "",
  }
];
