export const MY_SKILLS_DATA = [
  {
    id: 1,
    type: "education",
    date: "2014 - 2018",
    title: "Bachelor degree",
    subtitle: "MIPT, Moscow Institute of Physics and Technology",
    text: "Diploma: Applied Mathematics and Physics",
    labels: ["Science"],
    photo: "",
    link: "",
  },
  {
    id: 2,
    type: "education",
    date: "2017",
    title: "True random number generator in FGPA",
    subtitle: "60th MIPT Scientific Conference (172-173 pages)",
    text: "",
    labels: ["Science"],
    photo: "",
    link: "https://abitu.net/public/admin/mipt-conference/FRKT.pdf",
  },
  {
    id: 3,
    type: "pet",
    date: "2022",
    title: "Portfolio page",
    subtitle: "This site",
    text: "React js + Material UI",
    labels: ["Web"],
    photo: "",
    link: "https://github.com/yashart/my_portfolio_site",
  },
  {
    id: 4,
    type: "pet",
    date: "2022",
    title: "LTE Signal auto-guided amplifier",
    subtitle: "",
    text: "Full path from design to implementation. Device + mobile app.",
    labels: ["Other"],
    photo: "static/imgs/amplifier.jpg",
    link: "",
  },
  {
    id: 5,
    type: "pet",
    date: "2021",
    title: "Low cost autonomous self-driving robot",
    subtitle: "",
    text: "All software (wheel drivers, joystick app and visual slam)",
    labels: ["ROS", "Open CV"],
    photo: "static/imgs/3a_robot.png",
    link: "",
  },
  {
    id: 6,
    type: "education",
    date: "2020",
    title: "Investigation of the possibility of determining the satellite position by visual keypoints",
    subtitle: "",
    text: "Writing algorithm for get visual descriptors using 3d model and textures, test it using data from blender animation",
    labels: ["Science", "OpenCV"],
    photo: "static/imgs/sputnik.png",
    link: "",
  },
  {
    id: 7,
    type: "pet",
    date: "2019",
    title: "Real-time 3D scene using several kinects and mono cameras",
    subtitle: "",
    text: "Use data from several kinects point clouds and high res cameras in one space to make all sides 3d",
    labels: ["ROS"],
    photo: "",
    link: "",
  },
  {
    id: 8,
    type: "volonteur",
    date: "2014-present",
    title: "Teacher of IT in summer school",
    subtitle: "Principal in 2019-2021",
    text: "Summer school is a big part of my life. Every year ~40 students of main universities of the country make a 3-week children's camp for 60-120 children. We are absolute indipendent and no one get money for this.",
    labels: ["Social"],
    photo: "static/imgs/will_code_for_food.jpg",
    link: "http://lmsh.edu.ru",
  },
  {
    id: 9,
    type: "work",
    date: "2020-present",
    title: "Agrobit LLC",
    subtitle: "Software engineer, head of software departament since 2022",
    text: "A lot of interesting and ambicious work:\n\n\
    1. Custom manipulator for egg collection\n\
    2. Visual egg detection and tracking\n\
    3. SLAM navigation using RTABMap\n\
    4. SLAM using google cartographer\n\
    5. Tools for create and edit map paths\n\
    6. Death chicken detection\n\
    7. Web interfaces for joystick and telemetry info\n\
    8. etc",
    labels: ["ROS"],
    photo: "static/imgs/agrobit.png",
    link: "",
  },
  {
    id: 10,
    type: "pet",
    date: "2021",
    title: "Online labeling tool for photos",
    subtitle: "",
    text: "Tool for crowd sorting photos from summer school. \n\
    Children choose category of photo and at the end they get google drive structured photo album.",
    labels: ["Web"],
    photo: "static/imgs/photo_labeling.png",
    link: "",
  },
  {
    id: 11,
    type: "work",
    date: "2016-2019",
    title: "NDA",
    subtitle: "Software engineer",
    text: "Tools for photogrammetric image processing.\n\
    Software for agricultural drones.",
    labels: ["OpenCV", "QT"],
    photo: "",
    link: ""
  }
];
